# Generated by Django 4.0.4 on 2022-05-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmeaning',
            name='meaning',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
