# Generated by Django 4.0.4 on 2022-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_wordmeaning_meaning_alter_wordmeaning_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmeaning',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
