# Generated by Django 4.0.4 on 2022-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_wordmeaning_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmeaning',
            name='synonyms',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
